routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ContributorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IssueController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    if (!Auth::user()) {
        return redirect('login');
    }
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => ['auth', 'route_permission']], function () {

    Route::get('/home', '\\' . HomeController::class . '@index')->name('home');

    Route::resource('project', '\\' . ProjectController::class);
    Route::resource('milestone', '\\' . MilestoneController::class);
    Route::resource('issue', '\\' . IssueController::class);
    Route::resource('note', '\\' . NoteController::class);
    Route::resource('time', '\\' . TimeController::class);
    Route::resource('contributor', '\\' . ContributorController::class);
    Route::resource('payment', '\\' . PaymentController::class);
    Route::resource('user', '\\' . UserController::class);

});

app/Http/Controllers/IssueController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FormRequest;
use App\Model\Repository\ContributorRepositoryEloquent;
use App\Model\Repository\LabelRepositoryEloquent;
use App\Model\Repository\ProjectRepositoryEloquent;
use App\Model\Service\Eloquent\EloquentIssueService;
use App\Providers\AppServiceProvider;

class IssueController extends CrudController
{
    /**
     * @return EloquentIssueService
     */
    protected function getService()
    {
        return app(EloquentIssueService::class);
    }

    protected function prepareDataForIndex(FormRequest $request, array $data)
    {
        /** @var ContributorRepositoryEloquent $contributorRepository */
        $contributorRepository = app(AppServiceProvider::CONTRIBUTOR_REPOSITORY);

        /** @var ProjectRepositoryEloquent $projectRepository */
        $projectRepository = app(AppServiceProvider::PROJECT_REPOSITORY);

        /** @var LabelRepositoryEloquent $labelRepository */
        $labelRepository = app(AppServiceProvider::LABEL_REPOSITORY);

        return array_merge(
            $data,
            [
                'assigneeList' => $contributorRepository->getItemsForSelect(),
                'projectsList' => $projectRepository->getItemsForSelect(),
                'labelList' => $labelRepository->getItemsForSelect(null, null, 'name'),
            ]
        );
    }
}

resources/views/gitpab/issue/index.blade.php
@extends('partial.crud.index', [
    'pageTitle' => __('messages.Issues')
])

@section('contentTableControl')
@endsection

@section('contentTableFilter')
    @include('gitpab.issue.index_filter_form')
@endsection

@section('contentTable')
    @include('gitpab.issue.index_table', [
        'columnTitleName' => 'title'
    ])
@endsection

resources/views/gitpab/issue/index_filter_form.blade.php
@extends('partial.form.base_filter')
@section('formBody')
    {!! Form::open(array('url' => route('issue.index'), 'method' => 'get')) !!}
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @include('partial.form.element.text', [
                    'name' => 'id',
                    'value' => $request->input('id'),
                    'label' => __('messages.ID'),
                ])
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @include('partial.form.element.text', [
                    'name' => 'issue_iid',
                    'value' => $request->input('issue_iid'),
                    'label' => __('messages.Issue number'),
                ])
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @include('partial.form.element.select', [
                    'name' => 'assignee[]',
                    'list' => $assigneeList,
                    'selected' => $request->input('assignee'),
                    'options' => ['multiple' => 'multiple'],
                    'label' => __('messages.Assignee'),
                ])
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @include('partial.form.element.select', [
                    'name' => 'projects[]',
                    'list' => $projectsList,
                    'selected' => $request->input('projects'),
                    'options' => ['multiple' => 'multiple'],
                    'label' => __('messages.Projects'),
                ])
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @include('partial.form.element.date_range', [
                    'name' => 'date_range',
                    'input' => [
                        'date_start' => $request->get('date_start'),
                        'date_end' => $request->get('date_end'),
                    ],
                    'label' => __('messages.Created At'),
                ])
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @include('partial.form.element.select', [
                    'name' => 'labels[]',
                    'list' => $labelList,
                    'selected' => $request->input('labels'),
                    'options' => ['multiple' => 'multiple'],
                    'label' => __('messages.Labels'),
                ])
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <span class="group-btn">
                    <button name="submit" value="1" type="submit" class="btn btn-primary">@lang('messages.Apply')</button>
                </span>
                <span class="group-btn">
                    <button name="submit" value="csv" type="submit" class="btn btn-default">@lang('messages.Export CSV')</button>
                </span>
                <span class="group-btn pull-right">
                    <a class="btn btn-default" href="{{ route('time.index') }}">@lang('messages.Reset')</a>
                </span>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
@endsection

resources/views/gitpab/issue/index_table.blade.php
@extends('partial.table.base')

@php
$columnTitleName = isset($columnTitleName) ? $columnTitleName : 'name';
$columnTitleLabel = isset($columnTitleLabel) ? $columnTitleLabel : __('messages.Title');
$createdExist = isset($itemsList->first()['created_at']);
@endphp

@section('tableThead')
    <tr>
        @include('partial.table.thcell', [
            'column' => 'id',
            'label' => __('messages.ID'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute,
        ])

        @include('partial.table.thcell', [
            'column' => 'iid',
            'label' => __('messages.Number'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => $columnTitleName,
            'label' => $columnTitleLabel,
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'estimate',
            'label' => __('messages.Estimate'),
        ])

        @include('partial.table.thcell', [
            'column' => 'labels',
            'label' => 'Labels',
        ])

        @include('partial.table.thcell', [
            'column' => 'assignee',
            'label' => __('messages.Assignee'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'project',
            'label' => __('messages.Project'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @if ($createdExist)
            @include('partial.table.thcell', [
                'column' => 'created_at',
                'label' => __('messages.Created At'),
            ])
        @endif
    </tr>
@endsection
@section('tableTbody')
    @forelse ($itemsList->items() as $key => $item)
        <tr>
            <td class="col-md-1">{{ $item->id }}</td>
            <td class="col-md-1">
                <a href="{{ $item->web_url }}">{{ $item->iid }}</a>
            </td>
            <td class="col-md-3">
                <a href="{{ route($showRoute, [$item->id]) }}">
                    {{ (isset($columnTitleName)) ? $item->{$columnTitleName} : $item->title }}
                </a>
            </td>
            <td class="col-md-1">
                {{ $item->estimate ?? null }}
            </td>
            <td class="col-md-2">
                @foreach ($item->labels as $label)
                    <span class="label label-primary">{{ $label }}</span>
                @endforeach
            </td>
            <td class="col-md-2">
                {{ $item->assignee->name ?? null }}
            </td>
            <td class="col-md-1">
                {{ $item->project->name ?? null }}
            </td>
            @if ($createdExist)
                <td class="col-md-1">
                    {{ $item->created_at }}
                </td>
            @endif
        </tr>
    @empty
        <tr>
            <td colspan="{{ $createdExist ? 8 : 7 }}" class="col-md-12">@lang('messages.Data not found')</td>
        </tr>
    @endforelse
@endsection

resources/views/gitpab/issue/show.blade.php
@extends('partial.crud.show', [
    'pageTitle' => __('messages.View issue')
])

@section('form')

    <div class="row">
        <div class="col-md-2">
            @lang('messages.ID')
        </div>
        <div class="col-md-10">
            {{ $object->id }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Title')
        </div>
        <div class="col-md-10">
            {{ $object->title }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Description')
        </div>
        <div class="col-md-10">
            {{ $object->description }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Assignee')
        </div>
        <div class="col-md-10">
            {{ $object->assignee->name ?? null }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Web url')
        </div>
        <div class="col-md-10">
            <a href="{{ $object->web_url }}">{{ $object->web_url }}</a>
        </div>
    </div>

@endsection