routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ContributorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IssueController;
use App\Http\Controllers\MilestoneController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TimeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    if (!Auth::user()) {
        return redirect('login');
    }
    return redirect('home');
});

Auth::routes();

Route::group(['middleware' => ['auth', 'route_permission']], function () {

    Route::get('/home', '\\' . HomeController::class . '@index')->name('home');

    Route::resource('project', '\\' . ProjectController::class);
    Route::resource('milestone', '\\' . MilestoneController::class);
    Route::resource('issue', '\\' . IssueController::class);
    Route::resource('note', '\\' . NoteController::class);
    Route::resource('time', '\\' . TimeController::class);
    Route::resource('contributor', '\\' . ContributorController::class);
    Route::resource('payment', '\\' . PaymentController::class);
    Route::resource('user', '\\' . UserController::class);

});

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FormRequest;
use App\Http\Requests\ListRequest;
use App\Http\Requests\StorePaymentRequest;
use App\Model\Repository\ContributorRepositoryEloquent;
use App\Model\Repository\PaymentStatusRepositoryEloquent;
use App\Model\Service\Eloquent\EloquentPaymentService;
use App\Providers\AppServiceProvider;

class PaymentController extends CrudController
{
    protected $requestMap = [
        'store' => StorePaymentRequest::class,
        'index' => ListRequest::class,
    ];

    /**
     * @return EloquentPaymentService
     */
    protected function getService()
    {
        return app(EloquentPaymentService::class);
    }

    protected function prepareDataForCreate(FormRequest $request, array $data)
    {
        /** @var PaymentStatusRepositoryEloquent $paymentStatusRepository */
        $paymentStatusRepository = app(AppServiceProvider::PAYMENT_STATUS_REPOSITORY);

        /** @var ContributorRepositoryEloquent $contributorRepository */
        $contributorRepository = app(AppServiceProvider::CONTRIBUTOR_REPOSITORY);

        return array_merge(
            $data,
            [
                'statusList' => $paymentStatusRepository->getItemsForSelect(null, null, 'id', 'title'),
                'contributorList' => $contributorRepository->getItemsForSelect(['' => '-']),
            ]
        );
    }

    protected function prepareDataForEdit(FormRequest $request, array $data)
    {
        /** @var PaymentStatusRepositoryEloquent $paymentStatusRepository */
        $paymentStatusRepository = app(AppServiceProvider::PAYMENT_STATUS_REPOSITORY);

        return array_merge(
            $data,
            [
                'statusList' => $paymentStatusRepository->getItemsForSelect(null, null, 'id', 'title'),
            ]
        );
    }
}

resources/views/gitpab/payment/create.blade.php
@extends('partial.crud.create', [
    'pageTitle' => __('messages.Create payment')
])

@section('form')

    <div class="row">
        <div class="col-md-6">
            @include('partial.form.element.text', [
                'name' => 'hours',
                'label' => __('messages.Payed hours'),
            ])
        </div>
        <div class="col-md-6">
            @include('partial.form.element.text', [
                'name' => 'title',
                'label' => __('messages.Short comment'),
            ])
        </div>
        <div class="col-md-6">
            @include('partial.form.element.select', [
                'name' => 'contributor_id',
                'label' => __('messages.Employer'),
                'list' => $contributorList ?? [],
            ])
        </div>
        <div class="col-md-6">
            @include('partial.form.element.select', [
                'name' => 'status_id',
                'label' => __('messages.Status'),
                'list' => $statusList ?? [],
            ])
        </div>
        <div class="col-md-6">
            @include('partial.form.element.date', [
                'name' => 'payment_date',
                'label' => __('messages.Payment date'),
            ])
        </div>
        <div class="col-md-12">
            @include('partial.form.element.textarea', [
                'name' => 'description',
                'label' => __('messages.Description'),
                'options' => [
                    'rows' => 5,
                ],
            ])
        </div>
    </div>

@endsection

resources/views/gitpab/payment/edit.blade.php
@extends('partial.crud.edit', [
    'pageTitle' => __('messages.Edit payment'),
])

@section('form')

    <div class="row">
        <div class="col-md-6">
            <label>@lang('messages.Hours')</label>
            <p>{{ $object->hours }}</p>
        </div>
        <div class="col-md-6">
            <label>@lang('messages.Short comment')</label>
            <p>{{ $object->name ?: '-' }}</p>
        </div>
        <div class="col-md-6">
            <label>@lang('messages.Payment date')</label>
            <p>{{ $object->payment_date }}</p>
        </div>
        <div class="col-md-6">
            <label>@lang('messages.Employer')</label>
            <p>{{ $object->contributor->name }}</p>
        </div>
        <div class="col-md-6">
            @include('partial.form.element.select', [
                'name' => 'status_id',
                'label' => __('messages.Status'),
                'list' => $statusList,
                'selected' => $object->status_id,
            ])
        </div>
    </div>

@endsection

resources/views/gitpab/payment/index.blade.php
@extends('partial.crud.index', [
    'pageTitle' => __('messages.Payments')
])

@section('contentTableControl')
    <a class="btn btn-primary" href="{{ route('payment.create')  }}">@lang('messages.Create')</a>
@endsection

@section('contentTable')
    @include('gitpab.payment.index_table', [
        'columnTitleLabel' => __('messages.Short comment')
    ])
@endsection

resources/views/gitpab/payment/index_table.blade.php
@extends('partial.table.base')

@php
$columnTitleName = isset($columnTitleName) ? $columnTitleName : 'name';
$columnTitleLabel = isset($columnTitleLabel) ? $columnTitleLabel : __('messages.Title');
@endphp

@section('tableThead')
    <tr>
        @include('partial.table.thcell', [
            'column' => 'id',
            'label' => __('messages.ID'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute,
        ])

        @include('partial.table.thcell', [
            'column' => 'hours',
            'label' => __('messages.Payed hours'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'user',
            'label' => __('messages.Employer'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => $columnTitleName,
            'label' => $columnTitleLabel,
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'status',
            'label' => __('messages.Status'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'payment_date',
            'label' => __('messages.Payment date'),
            'order' => $order,
            'orderDirection' => $orderDirection,
            'orderLinkRoute' => $indexRoute
        ])

        @include('partial.table.thcell', [
            'column' => 'created_at',
            'label' => __('messages.Created At'),
        ])

        @include('partial.table.thcell', [
            'column' => 'updated_at',
            'label' => __('messages.Updated At'),
        ])

        <th></th>
    </tr>
@endsection
@section('tableTbody')
    @forelse ($itemsList->items() as $key => $item)
        <tr>
            <td class="col-md-1"><a href="{{ route('payment.show', $item->id) }}">{{ $item->id }}</a></td>
            <td class="col-md-1">{{ $item->hours }}</td>
            <td class="col-md-2">{{ $item->contributor->name }}</td>
            <td class="col-md-3">{{ $item->title }}</td>
            <td class="col-md-1">@lang($item->status->title)</td>
            <td class="col-md-1">{{ $item->payment_date }}</td>
            <td class="col-md-1">
                {{ $item->created_at }} /
                {{ $item->created_by->name }}
            </td>
            <td class="col-md-1">
                {{ $item->updated_at }} /
                {{ $item->updated_by->name }}
            </td>
            <td class="col-md-1">
                <a href="{{ route($editRoute, [$item->id]) }}"
                   class="btn btn-xs text-success"
                   data-token="{{ csrf_token() }}">
                    <i class="fa fa-edit"></i>
                </a>
            </td>

        </tr>
    @empty
        <tr>
            <td colspan="9" class="col-md-12">@lang('messages.Data not found')</td>
        </tr>
    @endforelse
@endsection

resources/views/gitpab/payment/show.blade.php
@extends('partial.crud.show', [
    'pageTitle' => __('messages.View payment')
])

@section('form')

    <div class="row">
        <div class="col-md-2">
            @lang('messages.ID')
        </div>
        <div class="col-md-10">
            {{ $object->id }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Short comment')
        </div>
        <div class="col-md-10">
            {{ $object->title }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Payed hours')
        </div>
        <div class="col-md-10">
            {{ $object->hours }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Employer')
        </div>
        <div class="col-md-10">
            {{ $object->contributor->name }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Description')
        </div>
        <div class="col-md-10">
            {{ $object->description }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Payment date')
        </div>
        <div class="col-md-10">
            {{ $object->payment_date }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Created At')
        </div>
        <div class="col-md-10">
            {{ $object->created_at }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Created By')
        </div>
        <div class="col-md-10">
            {{ $object->created_by->name }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Updated At')
        </div>
        <div class="col-md-10">
            {{ $object->updated_at }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            @lang('messages.Updated By')
        </div>
        <div class="col-md-10">
            {{ $object->updated_by->name }}
        </div>
    </div>

@endsection